[project]
name = "blueprint"
version = "0.2.0"
description = "A library that implements a variety of superconducting circuit models and the tools required to perform fast and detailed simulations of their dynamics."
authors = [
    { name = "Boris Varbanov", email = "Boris.Mihailov.Varbanov@USherbrooke.ca" },
    { name = "Alex Chapple", email = "Alex.Arimoto.Chapple@USherbrooke.ca" },
    { name = "Élie Genois", email = "Elie.Genois@USherbrooke.ca" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "cython (>=3.2.1,<4.0.0)",
    "numpy (>=2.3.5,<3.0.0)",
    "scipy (>=1.16.3,<2.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "jax (>=0.4.36,<0.7) ; extra != 'cuda'",
    "jaxtyping (>=0.3.3,<0.4.0)",
    "equinox (>=0.13.2,<0.14.0)",
    "dynamiqs (>=0.3.4,<0.4.0)",
    "optax (>=0.2.6,<0.3.0)",
    "optimistix (>=0.0.11,<0.0.12)"
]

[project.optional-dependencies]
cuda = [
    "jax[cuda12] (>=0.4.36,<0.7)",
]
plot = [
    "matplotlib>=3.10.8",
]
notebook = [
    "ipykernel>=7.1.0",
]

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"
