[project]
name = "blueprint"
version = "0.2.0"
description = "A library implement a variety of superconducting circuit models and the tools required to perform fast and detail simulations of their dynamics."
license = "MIT"
readme = "README.md"
authors = [
    { name = "Boris Varbanov", email = "Boris.Mihailov.Varbanov@USherbrooke.ca" },
    { name = "Élie Genois", email = "Elie.Genois@USherbrooke.ca" },
]
requires-python = ">=3.13.7"
dependencies = [
    "cython>=3.1.5",
    "dynamiqs>=0.3.3",
    "equinox>=0.13.2",
    "jax>=0.8.0",
    "jaxtyping>=0.3.3",
    "numpy>=2.3.4",
    "optax>=0.2.6",
    "pyyaml>=6.0.3",
    "scipy>=1.16.2",
]

[project.optional-dependencies]
notebook = []

[build-system]
requires = ["uv_build>=0.8.21,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "pytest>=8.4.2",
]

[tool.uv]
